import { describe, expect, it } from 'vitest';
import { exportGhosttyConfig } from '@/lib/utils/config-export';
import { GHOSTTY_COMPATIBILITY_VERSION } from '@/lib/compatibility';
import { SPECTRE_VERSION } from '@/lib/version';
import { analyzeGhosttyConfig } from '@/lib/utils/config-import-analysis';

describe('exportGhosttyConfig', () => {
  it('renders Ghostty config output without depending on the Zustand store', () => {
    const output = exportGhosttyConfig(
      {
        'font-family': ['JetBrains Mono', 'Symbols Nerd Font'],
        keybind: ['ctrl+shift+e=text:FOO=bar', 'clear'],
        palette: ['0xF=ffffff'],
        'gtk-custom-css': ['"?required.css"', '?optional.css'],
        'unknown-option': 'raw = value',
      },
      'Dracula',
    );

    expect(output).toContain(`# Generated by Spectre v${SPECTRE_VERSION}`);
    expect(output).toContain(
      `# Spectre schema target: Ghostty ${GHOSTTY_COMPATIBILITY_VERSION}`
    );
    expect(output).toContain(
      '# Warning: contains 1 option outside this schema target; validate with your Ghostty build.'
    );
    expect(output).toContain('# Theme: Dracula');
    expect(output).toContain('font-family = "JetBrains Mono"');
    expect(output).toContain('font-family = "Symbols Nerd Font"');
    expect(output).toContain('keybind = ctrl+shift+e=text:FOO=bar');
    expect(output).toContain('keybind = clear');
    expect(output).toContain('palette = 15=#ffffff');
    expect(output).toContain('gtk-custom-css = ""?required.css""');
    expect(output).toContain('gtk-custom-css = ?optional.css');
    expect(analyzeGhosttyConfig(output).candidateConfig['gtk-custom-css']).toEqual([
      '"?required.css"',
      '?optional.css',
    ]);
    expect(output).toContain('unknown-option = "raw = value"');
  });

  it('round-trips normalized unverified string edge cases', () => {
    const analysis = analyzeGhosttyConfig(`
future-embedded = "say "hello" = now"
future-empty = ""
future-comment = #not-an-inline-comment
future-leading-space = "  padded value  "
future-unmatched-double = "literal
future-unmatched-single = '
`);

    const exported = exportGhosttyConfig(analysis.normalizedConfig);
    const reanalyzed = analyzeGhosttyConfig(exported);

    expect(reanalyzed.normalizedConfig).toEqual(analysis.normalizedConfig);
  });

  it('exports only the retained value for repeated unverified options', () => {
    const analysis = analyzeGhosttyConfig(`
future-option = first
future-option = "second = value"
`);

    const output = exportGhosttyConfig(analysis.normalizedConfig);

    expect(output).toContain(
      '# Warning: contains 1 option outside this schema target; validate with your Ghostty build.'
    );
    expect(output).toContain('future-option = "second = value"');
    expect(output).not.toContain('future-option = first');
  });

  it('warns about newer-than-target options without dropping them', () => {
    const output = exportGhosttyConfig(
      { 'font-size': 16, 'background-image': '/tmp/bg.png', 'progress-style': true },
      null,
      '1.1.0'
    );

    expect(output).toContain(
      '# Warning: 2 options require Ghostty newer than 1.1.0: background-image, progress-style.'
    );
    expect(output).toContain('font-size = 16');
    expect(output).toContain('background-image = /tmp/bg.png');
    expect(output).toContain('progress-style = true');
  });

  it('stays silent when everything is supported or no target is given', () => {
    const supported = exportGhosttyConfig({ 'font-size': 16 }, null, '1.0.0');
    expect(supported).not.toContain('newer than');

    const untargeted = exportGhosttyConfig(
      { 'progress-style': true },
      null,
      undefined
    );
    expect(untargeted).not.toContain('newer than');
    expect(untargeted).toContain('progress-style = true');

    const unknownTarget = exportGhosttyConfig({ 'progress-style': 'bar' }, null, 'tip');
    expect(unknownTarget).not.toContain('newer than');
  });

  it('warns at patch granularity for patch-release options', () => {
    const older = exportGhosttyConfig({ 'window-titlebar-background': '#000000' }, null, '1.0.0');
    expect(older).toContain(
      '# Warning: 1 option requires Ghostty newer than 1.0.0: window-titlebar-background.'
    );

    const current = exportGhosttyConfig({ 'window-titlebar-background': '#000000' }, null, '1.0.1');
    expect(current).not.toContain('newer than');
  });

  it('keeps the unknown-option warning separate from version warnings', () => {
    const output = exportGhosttyConfig(
      { 'future-option': 'x', 'progress-style': true },
      null,
      '1.0.0'
    );

    expect(output).toContain(
      '# Warning: contains 1 option outside this schema target; validate with your Ghostty build.'
    );
    expect(output).toContain(
      '# Warning: 1 option requires Ghostty newer than 1.0.0: progress-style.'
    );
  });
  it('omits values with line breaks instead of writing injected lines', () => {
    const output = exportGhosttyConfig({
      title: 'Harmless\ncommand = /tmp/evil.sh',
      keybind: ['ctrl+a=copy_to_clipboard', 'ctrl+b=paste\rinitial-command = x'],
      'font-size': 14,
    });

    expect(output).toContain(
      '# Warning: omitted 2 options with line breaks in the value: keybind, title.'
    );
    expect(output).toContain('font-size = 14');
    expect(output).not.toMatch(/^command = /m);
    expect(output).not.toContain('keybind = ctrl+a=copy_to_clipboard');
    expect(output).not.toContain('\r');
    expect(Object.keys(analyzeGhosttyConfig(output).candidateConfig)).toEqual(['font-size']);
  });
});
