import { readFile } from "node:fs/promises";
import { expect, test, type Route } from "@playwright/test";
import compatibility from "../compatibility.json";
import { encodeConfig } from "../src/lib/utils/url-share";

test("a user can open the configuration editor", async ({ page }) => {
  await page.goto("/");

  await expect(
    page.getByRole("heading", { name: /craft your ghostty experience/i })
  ).toBeVisible();

  await page.getByRole("link", { name: "Open Editor" }).first().click();

  await expect(page).toHaveURL(/\/editor$/);
  await expect(page.getByRole("heading", { name: "Fonts" })).toBeVisible();
});

test("a user can edit, inspect, share, and reopen a configuration", async ({
  page,
}) => {
  await page.goto("/editor");

  const fontSize = page.locator("#option-font-size").getByRole("spinbutton");
  await fontSize.fill("16");

  await expect(page.getByText("1 modified", { exact: true })).toBeVisible();
  await page.getByRole("button", { name: /view config/i }).click();
  await expect(page.getByRole("heading", { name: "Generated Config" })).toBeVisible();
  await expect(page.locator("pre")).toContainText(
    `Spectre schema target: Ghostty ${compatibility.ghostty.stableVersion}`
  );
  await expect(page.locator("pre")).toContainText("font-size = 16");

  await page.getByRole("button", { name: "Share", exact: true }).click();
  await expect(page.getByRole("button", { name: "Link Copied!" })).toBeVisible();

  const shareUrl = await page.evaluate(() => navigator.clipboard.readText());
  const parsedShareUrl = new URL(shareUrl);
  expect(parsedShareUrl.pathname).toBe("/share/custom-config");
  expect(parsedShareUrl.searchParams.get("c")).toBeTruthy();

  await page.goto(shareUrl);
  await expect(
    page.getByRole("heading", { name: "Custom Configuration" })
  ).toBeVisible();
  await expect(page.locator("pre")).toContainText("font-size = 16");
  const robots = await page.locator('meta[name="robots"]').getAttribute("content");
  expect(robots).toContain("noindex");
  expect(robots).toContain("nofollow");

  // The readable slug is descriptive; the validated payload is authoritative.
  const renamedShareUrl = new URL(shareUrl);
  renamedShareUrl.pathname = "/share/renamed-config";
  await page.goto(renamedShareUrl.toString());
  await expect(
    page.getByRole("heading", { name: "Custom Configuration" })
  ).toBeVisible();
  await expect(page.locator("pre")).toContainText("font-size = 16");

  // Query-only links generated by earlier Spectre versions remain valid.
  const legacyPayload = parsedShareUrl.searchParams.get("c");
  const legacyShareUrl = `${parsedShareUrl.origin}/share?c=${legacyPayload}`;
  await page.goto(legacyShareUrl);
  await expect(
    page.getByRole("heading", { name: "Custom Configuration" })
  ).toBeVisible();
  await expect(page.locator("pre")).toContainText("font-size = 16");

  await page.getByRole("button", { name: "Open Editor", exact: true }).click();
  await expect(page).toHaveURL(/\/editor$/);
  await expect(
    page.locator("#option-font-size").getByRole("spinbutton")
  ).toHaveValue("16");
});

test("the payload theme remains authoritative when a share slug is renamed", async ({
  page,
}) => {
  const search = new URLSearchParams({
    c: encodeConfig({ "font-size": 14 }, "Dracula"),
  });

  await page.goto(`/share/not-dracula?${search.toString()}`);

  await expect(
    page.getByRole("heading", { name: "Theme: Dracula" })
  ).toBeVisible();
  await expect(page.locator("pre")).toContainText("font-size = 14");
});

test("a user can import and export a Ghostty configuration", async ({ page }) => {
  await page.goto("/editor");

  const importedFile = {
    name: "config",
    mimeType: "text/plain",
    buffer: Buffer.from("font-size = 18\ncursor-style = bar\n"),
  };

  const importButton = page.getByRole("button", { name: "Import Config" });
  let fileChooserPromise = page.waitForEvent("filechooser");
  await importButton.click();
  let fileChooser = await fileChooserPromise;
  await fileChooser.setFiles(importedFile);

  await expect(
    page.getByRole("heading", { name: "Review imported configuration" })
  ).toBeVisible();
  await expect(page.getByText("font-size = 18")).toBeVisible();
  await expect(page.getByText("cursor-style = bar")).toBeVisible();

  await page.getByRole("button", { name: "Cancel" }).click();
  await expect(
    page.getByRole("heading", { name: "Review imported configuration" })
  ).not.toBeVisible();
  await expect(
    page.locator("#option-font-size").getByRole("spinbutton")
  ).toHaveValue("13");
  await expect(importButton).toBeFocused();

  fileChooserPromise = page.waitForEvent("filechooser");
  await importButton.click();
  fileChooser = await fileChooserPromise;
  await fileChooser.setFiles(importedFile);
  await page.getByRole("button", { name: "Replace with 2 settings" }).click();

  await expect(page.getByText("2 modified", { exact: true })).toBeVisible();
  await expect(page.getByText("Imported 2 settings.", { exact: true })).toBeAttached();
  await expect(importButton).toBeFocused();
  await expect(
    page.locator("#option-font-size").getByRole("spinbutton")
  ).toHaveValue("18");

  const downloadPromise = page.waitForEvent("download");
  await page.getByRole("button", { name: "Export Config" }).click();
  const download = await downloadPromise;
  const downloadPath = await download.path();

  expect(download.suggestedFilename()).toBe("config");
  expect(downloadPath).not.toBeNull();
  const downloadedConfig = await readFile(downloadPath!, "utf8");
  expect(downloadedConfig).toContain(
    `Spectre schema target: Ghostty ${compatibility.ghostty.stableVersion}`
  );
  expect(downloadedConfig).toContain("font-size = 18");
  expect(downloadedConfig).toContain("cursor-style = bar");
});

test("a user can explicitly import valid settings from a partially invalid file", async ({
  page,
}) => {
  await page.goto("/editor");

  const fileChooserPromise = page.waitForEvent("filechooser");
  await page.getByRole("button", { name: "Import Config" }).click();
  const fileChooser = await fileChooserPromise;
  await fileChooser.setFiles({
    name: "config",
    mimeType: "text/plain",
    buffer: Buffer.from(
      "font-size = 16\nmouse-hide-while-typing = maybe\ncursor-style = bar\n"
    ),
  });

  await expect(
    page.getByRole("list", { name: "Import issues" })
  ).toContainText(
    "Error — Line 2 · mouse-hide-while-typing: Use 1, 0, t, T, f, F, true, or false."
  );
  await page
    .getByRole("button", { name: "Replace with 2 settings and skip 1 line" })
    .click();

  await expect(page.getByText("2 modified", { exact: true })).toBeVisible();
  await expect(
    page.getByText("Imported 2 settings and skipped 1 line.", {
      exact: true,
    })
  ).toBeAttached();
  await page.getByRole("button", { name: "View Config" }).click();
  await expect(page.locator("pre")).toContainText("font-size = 16");
  await expect(page.locator("pre")).toContainText("cursor-style = bar");
  await expect(page.locator("pre")).not.toContainText("mouse-hide-while-typing");
});

test("a user can retain unverified options while unsafe names are rejected", async ({
  page,
}) => {
  await page.goto("/editor");

  const fileChooserPromise = page.waitForEvent("filechooser");
  await page.getByRole("button", { name: "Import Config" }).click();
  const fileChooser = await fileChooserPromise;
  await fileChooser.setFiles({
    name: "config",
    mimeType: "text/plain",
    buffer: Buffer.from(
      'font-szie = 15\nfuture-option = first\nfuture-option = "second = value"\n__proto__ = polluted\nconstructor = polluted\n'
    ),
  });

  const typoInstruction = page.getByRole("link", {
    name: "font-szie",
    exact: true,
  });
  await expect(typoInstruction.locator("..")).toContainText("font-szie = 15");
  const futureInstruction = page.getByRole("link", {
    name: "future-option",
    exact: true,
  });
  await expect(futureInstruction).toHaveCount(1);
  await expect(futureInstruction.locator("..")).toContainText(
    "future-option = second = value"
  );
  await expect(page.getByText("Unverified", { exact: true })).toHaveCount(2);
  await expect(
    page.getByRole("list", { name: "Import issues" })
  ).toContainText(
    "Error — Line 4 · __proto__: This option name is reserved and cannot be imported safely."
  );

  await page
    .getByRole("button", { name: "Replace with 2 settings and skip 2 lines" })
    .click();
  await expect(page.getByText("2 modified", { exact: true })).toBeVisible();

  await page.getByRole("button", { name: "View Config" }).click();
  const output = page.locator("pre");
  await expect(output).toContainText(
    "Warning: contains 2 options outside this schema target"
  );
  await expect(output).toContainText("font-szie = 15");
  await expect(output).toContainText('future-option = "second = value"');
  await expect(output).not.toContainText("future-option = first");
  await expect(output).not.toContainText("__proto__");
  await expect(output).not.toContainText("constructor =");
});

test("a user can navigate and inspect configuration on a mobile screen", async ({
  page,
}) => {
  await page.setViewportSize({ width: 390, height: 844 });
  await page.goto("/editor");

  await page.getByRole("button", { name: "Colors", exact: true }).click();
  await expect(page.getByRole("heading", { name: "Colors" })).toBeVisible();

  await page.getByRole("button", { name: "View Config" }).click();
  await expect(page.getByRole("heading", { name: "Generated Config" })).toBeVisible();
  await expect(page.getByText("No modifications yet")).toBeVisible();
  await page.waitForTimeout(600);

  const hasHorizontalPageOverflow = await page.evaluate(
    () => document.documentElement.scrollWidth > window.innerWidth
  );
  expect(hasHorizontalPageOverflow).toBe(false);
});

test("a user can retry the terminal preview after WASM loading fails", async ({
  page,
}) => {
  const wasmUrl = "**/ghostty-vt.wasm";
  const failWasmRequest = (route: Route) => route.abort("failed");
  await page.route(wasmUrl, failWasmRequest);
  await page.goto("/editor");

  await page.getByRole("button", { name: "Open Preview" }).click();
  await expect(page.getByText("Failed to load preview")).toBeVisible();

  await page.unroute(wasmUrl, failWasmRequest);
  await page.getByRole("button", { name: "Retry" }).click();
  await expect(page.getByText("Failed to load preview")).not.toBeVisible({
    timeout: 15_000,
  });
  await expect(page.getByText("Loading Ghostty WASM...")).not.toBeVisible();
});
