#!/usr/bin/env bun
// Generates src/data/ghostty-builtin-themes.ts: the theme names bundled with
// the pinned Ghostty release (the `iterm2_themes` dependency in build.zig.zon).
// Pass --check to fail instead of writing when the committed list is stale.

import { readFile, writeFile } from "node:fs/promises";
import { gunzipSync } from "node:zlib";
import compatibility from "../compatibility.json";

const OUTPUT = new URL("../src/data/ghostty-builtin-themes.ts", import.meta.url);
const ZON_URL = `https://raw.githubusercontent.com/ghostty-org/ghostty/${compatibility.ghostty.configCommit}/build.zig.zon`;
const HEADERS = { "User-Agent": "Mozilla/5.0 (spectre-ghostty-config theme list)" };

async function fetchOk(url: string): Promise<Response> {
  const response = await fetch(url, { headers: HEADERS, signal: AbortSignal.timeout(60_000) });
  if (!response.ok) throw new Error(`Failed to fetch ${url}: ${response.status} ${response.statusText}`);
  return response;
}

/** Regular-file paths in a tar archive (ustar headers, 512-byte blocks). */
function tarFilePaths(archive: Uint8Array): string[] {
  const decoder = new TextDecoder();
  const field = (offset: number, length: number) => {
    const text = decoder.decode(archive.subarray(offset, offset + length));
    const nul = text.indexOf("\0");
    return nul === -1 ? text : text.slice(0, nul);
  };
  const paths: string[] = [];
  let offset = 0;
  while (offset + 512 <= archive.length) {
    const name = field(offset, 100);
    if (!name) break;
    const size = parseInt(field(offset + 124, 12).trim() || "0", 8);
    const type = field(offset + 156, 1);
    const prefix = field(offset + 345, 155);
    if (type === "0" || type === "") paths.push(prefix ? `${prefix}/${name}` : name);
    offset += 512 + Math.ceil(size / 512) * 512;
  }
  return paths;
}

async function main() {
  const zon = await (await fetchOk(ZON_URL)).text();
  const url = /\.iterm2_themes\s*=\s*\.\{\s*\.url\s*=\s*"([^"]+)"/.exec(zon)?.[1];
  if (!url) throw new Error("iterm2_themes dependency not found in build.zig.zon");

  const archive = gunzipSync(new Uint8Array(await (await fetchOk(url)).arrayBuffer()));
  const names = tarFilePaths(archive)
    .map((path) => path.split("/").pop()!)
    .filter((name) => name && !name.startsWith("."))
    .sort((a, b) => a.localeCompare(b, "en"));
  if (names.length < 100 || new Set(names).size !== names.length) {
    throw new Error(`Unexpected theme bundle contents (${names.length} names)`);
  }

  const output = `// Generated by scripts/generate-ghostty-builtin-themes.ts. Do not edit.
// Themes bundled with Ghostty ${compatibility.ghostty.tag} (${compatibility.ghostty.configCommit}),
// from the build.zig.zon iterm2_themes dependency:
// ${url}

export const GHOSTTY_BUILTIN_THEMES: readonly string[] = [
${names.map((name) => `  ${JSON.stringify(name)},`).join("\n")}
];
`;

  if (process.argv.includes("--check")) {
    const current = await readFile(OUTPUT, "utf8").catch(() => "");
    if (current !== output) {
      console.error(
        "Built-in theme list is out of date with the pinned Ghostty source.\n" +
          "Run `bun run themes:builtin` and review the diff."
      );
      process.exit(1);
    }
    console.log(`Built-in themes match Ghostty ${compatibility.ghostty.tag} (${names.length}).`);
    return;
  }

  await writeFile(OUTPUT, output);
  console.log(`Wrote ${names.length} themes to ${OUTPUT.pathname}`);
}

main().catch((error) => {
  console.error(error instanceof Error ? error.message : error);
  process.exit(1);
});
