#!/usr/bin/env bun
// Generates src/data/ghostty-default-keybinds.ts from Ghostty's pinned
// Config.zig (Keybinds.init). Pass --check to fail instead of writing when
// the committed table no longer matches the pinned source.

import { readFile, writeFile } from "node:fs/promises";
import compatibility from "../compatibility.json";
import {
  evaluateGhosttyDefaultKeybinds,
  extractActionDefaultParams,
  extractKeybindsInitBody,
  type GhosttyPlatform,
} from "../src/lib/utils/ghostty-default-keybinds-extract";

const OUTPUT = new URL("../src/data/ghostty-default-keybinds.ts", import.meta.url);
const SOURCE_BASE = `https://raw.githubusercontent.com/ghostty-org/ghostty/${compatibility.ghostty.configCommit}/src`;
const PLATFORMS: GhosttyPlatform[] = ["macos", "linux"];

async function main() {
  const fetchSource = async (path: string) => {
    const response = await fetch(`${SOURCE_BASE}/${path}`, {
      headers: { "User-Agent": "spectre-ghostty-config-default-keybinds" },
      signal: AbortSignal.timeout(30_000),
    });
    if (!response.ok) {
      throw new Error(`Failed to fetch ${path}: ${response.status} ${response.statusText}`);
    }
    return response.text();
  };
  const [configSource, bindingSource] = await Promise.all([
    fetchSource("config/Config.zig"),
    fetchSource("input/Binding.zig"),
  ]);
  const body = extractKeybindsInitBody(configSource);
  const defaultParams = extractActionDefaultParams(bindingSource);

  const tables = PLATFORMS.map((platform) => {
    const rows = evaluateGhosttyDefaultKeybinds(body, platform)
      .map((binding) => `    { trigger: ${JSON.stringify(binding.trigger)}, action: ${JSON.stringify(binding.action)} },`)
      .join("\n");
    return `  ${platform}: [\n${rows}\n  ],`;
  });

  const output = `// Generated by scripts/generate-ghostty-default-keybinds.ts. Do not edit.
// Source: Ghostty ${compatibility.ghostty.tag} (${compatibility.ghostty.configCommit})
// src/config/Config.zig Keybinds.init, evaluated per platform. Later
// bindings for the same trigger replace earlier ones, as in Ghostty.
// Action default parameters come from src/input/Binding.zig.

import type {
  GhosttyDefaultKeybind,
  GhosttyPlatform,
} from "@/lib/utils/ghostty-default-keybinds-extract";

export const GHOSTTY_DEFAULT_KEYBINDS: Record<GhosttyPlatform, readonly GhosttyDefaultKeybind[]> = {
${tables.join("\n")}
};

/** Actions whose omitted parameter means this value, e.g. \`copy_to_clipboard\` = \`copy_to_clipboard:mixed\`. */
export const GHOSTTY_ACTION_DEFAULT_PARAMS: Readonly<Record<string, string>> = ${JSON.stringify(defaultParams, null, 2).replace(/\n/g, "\n")};
`;

  if (process.argv.includes("--check")) {
    const current = await readFile(OUTPUT, "utf8").catch(() => "");
    if (current !== output) {
      console.error(
        "Default keybinds are out of date with the pinned Ghostty source.\n" +
          "Run `bun run keybinds:defaults` and review the diff."
      );
      process.exit(1);
    }
    console.log(`Default keybinds match Ghostty ${compatibility.ghostty.tag}.`);
    return;
  }

  await writeFile(OUTPUT, output);
  console.log(`Wrote ${OUTPUT.pathname}`);
}

main().catch((error) => {
  console.error(error instanceof Error ? error.message : error);
  process.exit(1);
});
